[project]
name = "genai-engineer-analysis"
version = "0.1.0"
description = "Analysis of GenAI engineer roles"
authors = [{ name = "Lonn", email = "lonn@genai.engineer" }]
dependencies = [
    "pandas",
    "openpyxl",
    "xlrd",
    "numpy",
    "pytz",
    "python-dateutil",
    "six",
    "pymupdf",
]
requires-python = ">=3.12" 