import pandas as pd
from pathlib import Path

# --- Configuration ---
WORKSPACE_DIR = Path(__file__).resolve().parent.parent
ANALYSIS_DIR = WORKSPACE_DIR / "data" / "analysis_results"
OUTPUT_MD = WORKSPACE_DIR / "REPORT.md"


def load_table(path: Path, max_rows: int = 100) -> str:
    if not path.exists():
        return f"*(Error: Could not find table at `{path}`)*"
    try:
        df = pd.read_csv(path)
        if df.empty:
            return "*(Table is empty)*"
        return df.head(max_rows).to_markdown(index=False)
    except Exception as exc:
        return f"*(Error: Failed to load table: {exc})*"


def load_prose(path: Path) -> str:
    """A simple function to read a text/markdown file."""
    if not path.exists():
        return f"*(Error: Could not find file at `{path}`)*"
    try:
        return path.read_text(encoding="utf-8")
    except Exception as exc:
        return f"*(Error: Failed to load file: {exc})*"


def main():
    """
    Assembles all analysis artifacts into a single, comprehensive markdown report.
    """
    ANALYSIS_DIR.mkdir(parents=True, exist_ok=True)

    # --- File Paths ---
    profile_dist_png = "data/analysis_results/profile_distribution.png"
    category_type_png = "data/analysis_results/category_type_distribution.png"
    job_task_phrase_png = "data/analysis_results/job_task_distribution.png"
    job_task_coverage_png = "data/analysis_results/job_task_jobs_distribution.png"
    tech_dist_png = "data/analysis_results/technology_distribution.png"
    soft_skill_png = "data/analysis_results/soft_skill_distribution.png"
    focus_dist_png = "data/analysis_results/focus_distribution.png"
    cooccurrence_heatmap_png = (
        "data/analysis_results/technology_cooccurrence_heatmap.png"
    )

    chi_squared_csv = ANALYSIS_DIR / "chi_squared_results.csv"
    norm_tasks_csv = ANALYSIS_DIR / "normalized_crosstab_job_task.csv"
    norm_tech_csv = ANALYSIS_DIR / "normalized_crosstab_technology.csv"
    norm_skills_csv = ANALYSIS_DIR / "normalized_crosstab_soft_skill.csv"
    top_tools_overall_csv = ANALYSIS_DIR / "top_tools_overall.csv"
    top_tools_profile_csv = ANALYSIS_DIR / "top_tools_by_profile.csv"
    topic_correlation_md = ANALYSIS_DIR / "topic_profile_correlation.md"

    # --- Build Report ---
    md = [
        "## GenAI/ML Engineer Job Market Analysis Report",
        "",
        "This report summarizes the CAIN-style metrics generated by the automated pipeline, including descriptive statistics, significance testing, and exploratory topic modeling.",
        "",
        "### Profile Distribution",
        "",
        f"![Profile Distribution]({profile_dist_png})",
        "",
        "**Interpretation:**",
        'This chart provides the highest-level summary of the analysis, showing the final classification for the ~1200 unique job ads. It answers the core question: "What is the composition of the AI engineering job market?"',
        "- A near-even split is observed between roles clearly identifiable as `GenAI Engineer` and those classified as `Ambiguous / Not Relevant`. This latter group often consists of generic software roles that mention AI trivially or job ads that lack sufficient detail.",
        "- `ML Engineer` roles represent a smaller, more specialized segment, indicating that while traditional ML is important, the current hiring focus leans heavily towards generative AI.",
        "- This distribution suggests that while GenAI is a major hiring trend, many companies are still refining the exact responsibilities of the role, leading to significant ambiguity in the job market.",
        "",
        "### Category Types",
        "",
        f"![Category Types]({category_type_png})",
        "",
        "**Interpretation:**",
        "This visual breaks down the total number of phrases and keywords extracted from all job ads, grouped into the three macro-categories defined in the `CODING_BOOK.md`: Job Tasks, Soft Skills, and Technologies. It shows that `Job Tasks` are the most frequently mentioned category, confirming that the dataset is rich with actionable information about the day-to-day responsibilities of these engineering roles.",
        "",
        "### Job Tasks (Phrase-level)",
        "",
        f"![Job Tasks (Phrases)]({job_task_phrase_png})",
        "",
        "**Interpretation:**",
        "This chart displays a direct count of every single phrase related to a job task, categorized according to the five-pillar framework from the CAIN2022 paper.",
        '- The high counts (e.g., ~4000 for `Software Development`) reveal the **intensity** of discussion around each task. A single job ad often contains multiple phrases describing different aspects of software development (e.g., "build APIs," "ensure code quality," "deploy applications").',
        "- This view highlights that even in specialized AI roles, core software engineering is a dominant and frequently repeated requirement, forming the foundation of the role.",
        "",
        "### Job Tasks (Per-job Coverage)",
        "",
        f"![Job Tasks (Jobs)]({job_task_coverage_png})",
        "",
        "**Interpretation:**",
        "This chart clarifies the data by showing how many **unique job ads** mention each task at least once.",
        "- This view reveals the **prevalence** or **breadth** of each requirement. `Software Development` being mentioned in over 1,000 unique jobs confirms it as a near-universal requirement.",
        '- In contrast, `Data Engineering` is mentioned in just over 300 jobs, indicating it is a more specialized or less frequently required skill for this cohort. This view helps distinguish between "must-have" and "nice-to-have" competencies.',
        "",
        "### Technologies",
        "",
        f"![Technologies]({tech_dist_png})",
        "",
        "**Interpretation:**",
        'This chart provides a strategic overview of the tech landscape by grouping specific tools into their parent "family". It clearly shows that the ideal candidate must be proficient across three key areas:',
        "1.  `LLM / Generative Models`: The core domain knowledge.",
        "2.  `Programming Languages`: The tools to build with (primarily Python).",
        "3.  `Cloud Platforms & Services`: The environment for deployment.",
        "",
        "### Soft Skills",
        "",
        f"![Soft Skills]({soft_skill_png})",
        "",
        "**Interpretation:**",
        "This chart shows the frequency of phrases related to interpersonal and non-technical skills. `Communication & Collaboration` and `Innovation & Ownership` are by far the most desired soft skills. This indicates that companies are seeking proactive, team-oriented engineers who can not only execute technical tasks but also understand business needs, solve problems creatively, and drive new ideas.",
        "",
        "### Focus per Job (RQ1b)",
        "",
        f"![Focus per Job]({focus_dist_png})",
        "",
        "**Interpretation:**",
        "This chart directly addresses Research Question 1b from the CAIN paper by classifying each job's focus based on the presence of `Modeling` (TASK3) and `Software Development` (TASK4) tasks. The result is clear: the vast majority of roles are a hybrid of `Data Science & Software Engineering`, confirming that the modern AI Engineer is not a pure specialist but a blended, engineering-focused role.",
        "",
        "---",
        "",
        "## Statistical Deep Dive",
        "",
        "To add scientific rigor, the following analyses were performed to test the significance of observed differences and uncover deeper patterns in the data.",
        "",
        "### Statistical Significance (Chi-Squared Tests)",
        "",
        "A Chi-Squared test was performed to determine if the observed differences in the distribution of tasks and skills between `GenAI Engineer` and `ML Engineer` profiles are statistically significant.",
        "",
        load_table(chi_squared_csv),
        "",
        "**Interpretation:**",
        "For both `job_task` and `soft_skill` categories, the p-value is effectively zero (p < 0.001). This indicates that the differences in which tasks and skills are required for GenAI Engineers versus ML Engineers are **highly statistically significant**. The variations we see are not due to random chance; they represent genuine, distinct requirements for each profile. (Note: The test for `technology` was skipped as some sub-categories had too few observations for a valid test).",
        "",
        "### Technology Co-occurrence Heatmap",
        "",
        f"![Technology Co-occurrence Heatmap]({cooccurrence_heatmap_png})",
        "",
        "**Interpretation:**",
        'This heatmap visualizes which technologies are most frequently mentioned together in the same job ad, revealing the "core toolkits" companies expect. The brighter the square, the more often the two technologies appear together.',
        "- Strong clusters can be observed, for instance, between `Kubernetes` and `Docker`, indicating a common containerization toolkit.",
        "- Other pairings, like `Python` with `PyTorch` and `TensorFlow`, are also prominent, highlighting the standard stack for ML development.",
        "",
        "### Normalized Profile Comparisons (Percentages)",
        "",
        "The following tables show the distribution of tasks, technologies, and skills *within* each profile. Each column is normalized to sum to 100%, making it easy to compare the relative importance of each category for a `GenAI Engineer` versus an `ML Engineer`.",
        "",
        "#### Job Tasks (Normalized)",
        "",
        load_table(norm_tasks_csv),
        "",
        "#### Technologies (Normalized)",
        "",
        load_table(norm_tech_csv),
        "",
        "#### Soft Skills (Normalized)",
        "",
        load_table(norm_skills_csv),
        "",
        "**Interpretation:**",
        "These tables offer clear, comparative insights:",
        "- **GenAI roles have a much stronger emphasis on `LLM / Generative Models` and `LLM Frameworks & Libraries`**. This is their defining characteristic.",
        "- **ML roles place a significantly higher importance on `Data Modeling` and `MLOps & Data Pipelines`**, highlighting their focus on traditional ML and productionalization.",
        "- For tasks, `Software Development` makes up a larger percentage of the GenAI role, whereas `Data Engineering` is far more critical for ML Engineers.",
        "",
        "---",
        "",
        "## Exploratory Analysis: Topic Modeling",
        "",
        "To discover hidden thematic structures in the raw job descriptions beyond our predefined schema, an exploratory analysis using Topic Modeling was performed. This technique allows the data to form its own clusters of co-occurring words, revealing natural themes.",
        "",
        "### Topic & Profile Correlation",
        "",
        "The following table shows the distribution of our established profiles across the 10 machine-discovered topics.",
        "",
        load_prose(topic_correlation_md),
        "",
        "**Interpretation:**",
        "This analysis provides a powerful, data-driven validation of our primary classification schema.",
        "- **Confirmation of `Not Relevant` Category:** Topics composed of non-technical terms show a strong correlation with the `Ambiguous / Not Relevant` profile. For example, topics related to HR/benefits or generic junior roles are overwhelmingly classified as `Not Relevant`. This confirms that our main pipeline correctly identifies and filters out job ads that are not true AI engineering roles.",
        '- **Identifying Profile Signatures:** The analysis also reveals the "signature" topics for our key profiles. The topic focused on **Product Building** and the **Dutch Model Training** topic are clear signals for a `GenAI Engineer` role. This data-driven discovery aligns perfectly with our `CODING_BOOK` definition of a GenAI engineer.',
        "",
    ]

    OUTPUT_MD.write_text("\n".join(md), encoding="utf-8")
    print(
        f"Full report, including all interpretations and statistical analyses, has been written to: {OUTPUT_MD}"
    )


if __name__ == "__main__":
    main()
